name: ci

on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    services:
      mqtt:
        image: eclipse-mosquitto:latest
        ports:
          - '1883:1883'
    env:
      MQTT_BROKER: tcp://localhost:1883
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Check out code
        uses: actions/checkout@v1
      - name: Get dependencies
        run: go mod download
      - name: Run tests
        run: go test -race
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    services:
      mqtt:
        image: eclipse-mosquitto:latest
        ports:
          - '1883:1883'
    env:
      MQTT_BROKER: tcp://localhost:1883
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Check out code
        uses: actions/checkout@v1
      - name: Get dependencies
        run: go mod download
      - name: Run coverage
        run: go test -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
